GENRES = [
{"id":0,"name":"Blues","desc":"Blues is a music genre and musical form which originated in the Deep South of the United States around the 1860s by African-Americans from roots in African-American work songs and spirituals. Blues incorporated spirituals, work songs, field hollers, shouts, chants, and rhymed simple narrative ballads."},
{"id":1,"name":"Classical","desc":"Classical music generally refers to the formal musical tradition of the Western world, considered to be distinct from Western folk music or popular music traditions."},
{"id":2,"name":"Country","desc":"Country is a genre of popular music that originated with blues, church music such as Southern gospel and spirituals, old-time, and American folk music forms including Appalachian, Cajun, Creole, and the cowboy Western music styles of New Mexico, Red Dirt, Tejano, and Texas country. "},
{"id":3,"name":"Disco","desc":"Disco is a genre of dance music and a subculture that emerged in the 1970s from the United States' urban nightlife scene. Its sound is typified by four-on-the-floor beats, syncopated basslines, string sections, horns, electric piano, synthesizers, and electric rhythm guitars. "},
{"id":4,"name":"Hiphop","desc":"Hip hop music or hip-hop music, also known as rap music, is a genre of popular music developed in the United States by inner-city African Americans and Caribbean Americans in the Bronx borough of New York City in the 1970s."},
{"id":5,"name":"Jazz","desc":"Jazz is a music genre that originated in the African-American communities of New Orleans, Louisiana in the late 19th and early 20th centuries, with its roots in blues and ragtime."},
{"id":6,"name":"Metal","desc":"Metal is a genre of rock music that developed in the late 1960s and early 1970s, largely in the United Kingdom and United States"},
{"id":7,"name":"Pop","desc":"Pop is a genre of popular music that originated in its modern form during the mid-1950s in the United States and the United Kingdom. The terms popular music and pop music are often used interchangeably, although the former describes all music that is popular and includes many disparate styles. "},
{"id":8,"name":"Reggae","desc":"Reggae is a music genre that originated in Jamaica in the late 1960s. The term also denotes the modern popular music of Jamaica and its diaspora."},
{"id":9,"name":"Rock","desc":"Rock music is a broad genre of popular music that originated as rock and roll in the United States in the late 1940s and early 1950s, developing into a range of different styles in the mid-1960s and later, particularly in the United States and the United Kingdom."}
]
